# Generated by Django 5.2 on 2025-04-15 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=50)),
                ('last', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=8)),
                ('timings', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('cuisine_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='TripMeUpApp.place')),
                ('working_hours', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='TripMeUpApp.user')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='TripMeUpApp.user')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tier', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_guests', models.IntegerField()),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TripMeUpApp.place')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TripMeUpApp.client')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='TripMeUpApp.city'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TripMeUpApp.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TripMeUpApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='TripMeUpApp.place')),
                ('type', models.CharField(max_length=100)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amenities', models.ManyToManyField(to='TripMeUpApp.amenities')),
            ],
        ),
        migrations.CreateModel(
            name='Serves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TripMeUpApp.cuisine')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TripMeUpApp.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Curates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TripMeUpApp.booking')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TripMeUpApp.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Writes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TripMeUpApp.review')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TripMeUpApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Browses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TripMeUpApp.city')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TripMeUpApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TripMeUpApp.cuisine')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TripMeUpApp.client')),
            ],
            options={
                'unique_together': {('client', 'cuisine')},
            },
        ),
    ]
