# Generated by Django 5.2 on 2025-04-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripMeUpApp', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
