# Generated by Django 5.2 on 2025-04-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripMeUpApp', '0003_city_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='intro',
            field=models.TextField(blank=True),
        ),
    ]
