# Generated by Django 5.2 on 2025-04-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripMeUpApp', '0004_city_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='facts',
            field=models.TextField(blank=True),
        ),
    ]
