# Generated by Django 5.2 on 2025-04-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripMeUpApp', '0006_place_description_place_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
