# Generated by Django 5.2 on 2025-04-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripMeUpApp', '0007_alter_place_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='test123', max_length=100),
        ),
    ]
