# Generated by Django 5.2 on 2025-04-22 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TripMeUpApp', '0008_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
