# Generated by Django 5.2 on 2025-04-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripMeUpApp', '0008_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
    ]
