# Generated by Django 5.2 on 2025-04-22 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TripMeUpApp', '0009_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='username',
        ),
        migrations.RemoveField(
            model_name='client',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tier',
        ),
    ]
