# Generated by Django 5.2 on 2025-04-22 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TripMeUpApp', '0010_remove_admin_salary_remove_admin_username_and_more'),
        ('TripMeUpApp', '0010_user_password'),
    ]

    operations = [
    ]
